# Generated by Django 2.2.4 on 2019-08-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=1024)),
                ('flag1', models.BooleanField()),
                ('flag2', models.BooleanField()),
                ('date_time', models.DateTimeField()),
                ('site_name', models.CharField(max_length=1024)),
                ('site_code', models.CharField(max_length=32)),
                ('h1_name', models.CharField(max_length=1024)),
            ],
        ),
    ]
